### ISSUE TITLE
Generate + distribute "phar" version as build artifact

### ISSUE THREAD

**Issue by mathiasbynens** [s9e/RegexpBuilderCommand#1]
This way, the `phar` file could be `npm publish`'d and more easily consumed in JS projects without requiring the installation of Composer.

Context: https://github.com/mathiasbynens/emoji-test-regex-pattern/pull/18

**Comment by JoshyPHP** [comment]
The GitHub Action is set and the README updated. You can now download the latest release directly and use it as a standalone tool.
```
$ wget -q https://github.com/s9e/RegexpBuilderCommand/releases/latest/download/build-regexp.phar
$ chmod +x build-regexp.phar
$ ./build-regexp.phar --version
build-regexp 0.4.3
```

I don't have any plans for NPM at the moment. It feels somewhat parasitic to use a JavaScript packager to distribute a PHP project. Is that something common in NPM?

**Comment by mathiasbynens** [comment]
Thanks for your work on this!
