### ISSUE TITLE
Add `standalone` option to avoid redundant non-capturing groups `(?:)` if the pattern is used as-is

### ISSUE THREAD

**Issue by mathiasbynens** [s9e/RegexpBuilderCommand#2]
(Spin-off from https://github.com/mathiasbynens/emoji-test-regex-pattern/pull/18#issuecomment-1052490090)

Please consider adding a `standalone` option which avoid outputting redundant non-capturing groups `(?:)` if the pattern is used as-is (i.e. is not embedded as part of a larger pattern).

> The `(?:)` is just a quirk from the library: all the alternations are constructed as non-capturing groups. Incidentally, it allows the generated expression to be used to compose a bigger regexp. For example, create a regexp made of a list of words, followed by `\b`. If parentheses were omitted at the root of the expression, one may end up with something like `xx|yy\b` which would be different from `(?:xx|yy)\b`. A future version may have a `standalone` option to indicate that the expression will be used whole and it would also output the regexp delimiters and flags where applicable (JS and PHP) but it's low priority at the moment.

Those are really two separate features that should be controlled by separate flags/options, IMHO. E.g. for emoji-test-regex-pattern, we _only_ want the option to suppress redundant `(?:)`. If that same option also starts outputting delimiters and flags, we’d need to post-process the output to remove those delimiters and flags.

**Comment by JoshyPHP** [comment]
Interesting. I didn't think there was a use case for a regular expression without parentheses *and* without delimiters/flags but I can see how that could be useful. For instance, when creating a regexp through a constructor such as `new RegExp(str)`.

Here's what I'm leaning towards at the moment. Three options:
 - `--standalone` - Whether the grouping parentheses can be omitted at the root. (default: false)
 - `--output-delimiters` - Whether to output delimiters. (default: false)
 - `--output-flags` - Whether to output flags. It would require `--output-delimiters`. (default: false)

I'm open to suggestions for the option names if you can think of anything more descriptive. I considered `--with-flags` but that would imply a `--without-flags` option, and that's not supported out of the box by the console library, although all of the options are disabled by default so users wouldn't actually need it.

**Comment by mathiasbynens** [comment]
For future reference, `--standalone` was added here: https://github.com/s9e/RegexpBuilderCommand/commit/3e58f83bab5be411250993ea90873b2ca5815dcb

Thanks!

**Comment by JoshyPHP** [comment]
Yes, I associated 69914a60e027107a695a3b4eb3c1e42da85a32c4 because this issue is really the reason those other flags exist.

Note that `--standalone` is enabled by default (I think that's the most common use case and what people expect), so you don't have to specify it. OTOH, if you were already post-processing the output to remove the extra parentheses you'll need to remove it when upgrading to 0.5.0.
